import streamlit as st
import os
from dotenv import load_dotenv
from urllib.parse import urlparse, parse_qs

from google import genai
from google.genai import types

from youtube_transcript_api import YouTubeTranscriptApi
from youtube_transcript_api._errors import TranscriptsDisabled, NoTranscriptFound


# -----------------------
# Environment Setup
# -----------------------

load_dotenv()
client = genai.Client(api_key=os.getenv("GEMINI_API_KEY"))


# -----------------------
# Helper Functions
# -----------------------

def extract_video_id(url: str) -> str | None:
    """
    Extracts the YouTube video ID from a URL.
    Returns None if the URL is not a valid YouTube link.
    """
    parsed_url = urlparse(url)

    # Short links: youtu.be/VIDEO_ID
    if parsed_url.hostname == "youtu.be":
        return parsed_url.path.lstrip("/")

    # Full links: youtube.com/watch?v=VIDEO_ID
    if parsed_url.hostname in ("www.youtube.com", "youtube.com"):
        query_params = parse_qs(parsed_url.query)
        video_ids = query_params.get("v")
        if video_ids:
            return video_ids[0]

    return None


def fetch_transcript(video_id: str) -> list[dict] | None:
    """
    Fetches the YouTube transcript for a given video ID.

    Strategy:
    1. Try direct fetch (fast path, recommended by docs)
    2. Fallback to transcript listing with explicit selection
    3. Prefer manual English, fallback to generated English

    Returns:
        List of dicts with keys: text, start, duration
        or None if no transcript is available.
    """
    ytt_api = YouTubeTranscriptApi()

    # --------
    # 1. Fast path: direct fetch (recommended default)
    # --------
    try:
        fetched = ytt_api.fetch(video_id, languages=["en"])
        return fetched.to_raw_data()
    except Exception:
        pass  # Fall back to manual selection

    # --------
    # 2. Fallback: explicit transcript selection
    # --------
    try:
        transcript_list = ytt_api.list(video_id)

        # Prefer manually created English transcript
        try:
            transcript = transcript_list.find_manually_created_transcript(["en"])
            return transcript.fetch().to_raw_data()
        except Exception:
            pass

        # Fallback to auto-generated English transcript
        try:
            transcript = transcript_list.find_generated_transcript(["en"])
            return transcript.fetch().to_raw_data()
        except Exception:
            pass

        return None

    except Exception:
        return None



def generate_notes(transcript_text: str) -> str:
    """
    Generates structured study notes from transcript text using Gemini.
    """
    prompt = f"""
You are a teaching assistant helping a student study.

Convert the following lecture transcript into clear, structured study notes.

Rules:
- Use clear topic headings
- Use bullet points under each heading
- Clearly define important terms
- Include examples if they are mentioned
- Keep explanations simple and student-friendly
- Do NOT include filler text, introductions, or conclusions
- Do NOT mention that these notes were generated by AI

Transcript:
{transcript_text}
"""

    response = client.models.generate_content(
        model="gemini-2.5-flash-lite",
        contents=prompt,
        config=types.GenerateContentConfig(
            temperature=0.3
        )
    )

    return response.text


# -----------------------
# Streamlit App UI
# -----------------------

st.set_page_config(page_title="Necture")

st.title("Necture")
st.write("Turn YouTube lectures into clean study notes.")

st.divider()

youtube_url = st.text_input(
    "Paste a YouTube video link:",
    placeholder="https://www.youtube.com/watch?v=..."
)

if youtube_url:
    video_id = extract_video_id(youtube_url)

    if not video_id:
        st.error("Please enter a valid YouTube video link.")
    else:
        st.success("Valid YouTube link detected!")
        st.write("Video ID:", video_id)

        transcript = fetch_transcript(video_id)

        if not transcript:
            st.warning("No transcript available for this video.")
        else:
            # Combining the text from the transcript segments
            full_text = " ".join(segment["text"] for segment in transcript)

            if st.button("Generate Study Notes"):
                with st.spinner("Generating notes..."):
                    try:
                        notes = generate_notes(full_text)
                        st.subheader("Study Notes")
                        st.write(notes)
                    except Exception as e:
                        st.error(f"An error occurred while generating notes: {e}")